(()=>{
 const button=document.createElement('button');button.id='nerida-version-switch';button.type='button';button.setAttribute('aria-label','切換至 Version 2');button.innerHTML='<span class="nv-mark" aria-hidden="true">V1</span><span class="nv-copy"><span class="nv-eyebrow">NERIDA</span><span class="nv-label">觀看 Version 2</span></span>';
 const status=document.createElement('div');status.id='nerida-version-status';status.hidden=true;status.setAttribute('role','status');status.setAttribute('aria-live','polite');status.innerHTML='<span class="nv-message"></span><div class="nv-track"><div class="nv-fill"></div></div>';
 const divider=document.createElement('div');divider.id='nerida-version-divider';divider.hidden=true;divider.setAttribute('aria-hidden','true');divider.innerHTML='<span class="nv-handle"><span>‹</span><span>›</span></span>';
 document.body.append(button,status,divider);
 const versionUrl=new URL('v2/index.html',document.baseURI).href;
 let frame=null,ready=false,loading=false,activeVersion=1,failed=false;
 const message=status.querySelector('.nv-message'),fill=status.querySelector('.nv-fill'),label=button.querySelector('.nv-label'),mark=button.querySelector('.nv-mark');
 function showStatus(text,value){status.hidden=false;message.textContent=text;if(Number.isFinite(value))fill.style.width=`${Math.max(0,Math.min(100,value))}%`;}
 function hideStatus(){status.hidden=true;}
 function syncButton(){mark.textContent=`V${activeVersion}`;label.textContent=activeVersion===1?(failed?'重試 Version 2':'觀看 Version 2'):'返回 Version 1';button.setAttribute('aria-label',activeVersion===1?(failed?'重新載入 Version 2':'切換至 Version 2'):'切換至 Version 1');}
 function ensureFrame(){if(frame)return frame;frame=document.createElement('iframe');frame.id='nerida-v2-frame';frame.title='NERIDA Version 2 互動 3D 巡覽';frame.allow='fullscreen; pointer-lock';frame.allowFullscreen=true;frame.setAttribute('aria-hidden','true');document.body.append(frame);return frame;}
 function completeAfterTransition(element,callback){let done=false;const finish=()=>{if(done)return;done=true;element.removeEventListener('transitionend',onEnd);callback();};const onEnd=e=>{if(e.target===element)finish();};element.addEventListener('transitionend',onEnd);setTimeout(finish,1000);}
 function revealV2(){if(!frame||!ready||loading)return;loading=true;button.disabled=true;hideStatus();divider.hidden=false;divider.classList.remove('nv-sweep-right');divider.classList.add('nv-active');frame.style.visibility='visible';frame.setAttribute('aria-hidden','false');requestAnimationFrame(()=>{requestAnimationFrame(()=>{divider.classList.add('nv-sweep-left');frame.classList.add('nv-visible');});});completeAfterTransition(frame,()=>{activeVersion=2;loading=false;button.disabled=false;divider.hidden=true;divider.classList.remove('nv-active','nv-sweep-left');syncButton();});}
 function returnV1(){if(!frame||loading)return;loading=true;button.disabled=true;hideStatus();divider.hidden=false;divider.classList.remove('nv-sweep-left');divider.classList.add('nv-active','nv-sweep-right');frame.classList.remove('nv-visible');frame.classList.add('nv-leaving');completeAfterTransition(frame,()=>{frame.style.visibility='hidden';frame.setAttribute('aria-hidden','true');frame.classList.remove('nv-leaving');divider.hidden=true;divider.classList.remove('nv-active','nv-sweep-right');activeVersion=1;loading=false;button.disabled=false;syncButton();});}
 function beginLoad(retry=false){frame=ensureFrame();ready=false;failed=false;loading=true;button.disabled=true;showStatus('正在準備 Version 2…',0);syncButton();frame.classList.remove('nv-visible','nv-leaving');frame.style.visibility='hidden';frame.setAttribute('aria-hidden','true');frame.src=retry?`${versionUrl}?retry=${Date.now()}`:versionUrl;}
 window.addEventListener('message',event=>{if(!frame||event.source!==frame.contentWindow||event.origin!==location.origin)return;const data=event.data;if(!data||data.type!=='nerida-v2')return;if(data.status==='progress'){if(!ready){const pct=Number(data.value)||0;showStatus(`Version 2 · ${Math.round(pct)}% · ${data.text||'載入中'}`,pct);}}else if(data.status==='preview'){ready=true;loading=false;failed=false;revealV2();}else if(data.status==='ready'){ready=true;failed=false;if(activeVersion===1&&!loading){loading=false;revealV2();}}else if(data.status==='error'){loading=false;failed=true;button.disabled=false;showStatus(`${ready?'Version 2 後續載入失敗':'Version 2 載入失敗'}：${data.message||'請重試'}`,0);syncButton();if(ready)setTimeout(hideStatus,9000);}});
 button.addEventListener('click',()=>{if(button.disabled)return;if(activeVersion===2){returnV1();return;}if(ready){revealV2();return;}beginLoad(failed);});
 syncButton();
})();
